### ISSUE TITLE
Paste doesn't work on macOS

### ISSUE THREAD

**Issue by jdosornio** [soywod/react-pin-field#13]
Cmd+V Does not trigger any paste when focusing the pin fields.
Paste works when you select paste from the secondary click context menu.

Ctrl+V Seems to work in Linux and Windows

**Comment by soywod** [comment]
Thank for the feedback, I will check this ASAP.

**Comment by soywod** [comment]
I don't have a Mac, it's hard for me to debug this. Could you please tell me what do you see when you press the `Cmd` key? https://keycode.info/

**Comment by soywod** [comment]
Got it! A missing condition was preventing the `onPaste` to trigger. The fix will be shipped in the `v1.0.0`.

**Comment by jdosornio** [comment]
Great! Thank you
