### ISSUE TITLE
Delete key is not triggering any event

### ISSUE THREAD

**Issue by sclavijo93** [soywod/react-pin-field#15]
If I complete the pin field and then I delete one of the fields with the Delete key the onChange event is not fired

### Code example:
[codesandbox.io](https://codesandbox.io/s/react-pin-field-bug-u6fu0)

### Steps to reproduce:
- Fill the pin fields
- Try to delete one field with the Delete key
- Look at the `current code` and `completed` rows

### Environment
| Tech        | Version |
| ----------- | ------- |
|Browser|Chrome Version 80.0.3987.149 (Official Build) (64-bit)|
|react|16.13.0|
|react-pin-field|1.0.1|

**Comment by soywod** [comment]
When you say `Delete key`, you mean the `Delete` evt.key (evt.which 46) or the `Backspace` evt.key (evt.which 8)?

**Comment by sclavijo93** [comment]
I mean Delete key (evt.which 46)

**Comment by soywod** [comment]
Indeed, the `Delete` key is not handled, I will fix ASAP. Thank you for the feedback!

**Comment by sclavijo93** [comment]
Thanks! I was looking at the code and what do think about adding the "Delete" case here?
[Lines](https://github.com/soywod/react-pin-field/blob/21c5765ff958e3b4cf66bc9d76f3d4d0565a12c3/src/pin-field/pin-field.tsx#L91;L93)

**Comment by soywod** [comment]
Fixed in `v1.0.2` :tada:

**Comment by sclavijo93** [comment]
@soywod  Great! Thank you so much! I love your component
