### ISSUE TITLE
Set up unit tests

### ISSUE THREAD

**Issue by soywod** [soywod/react-pin-field#2]

**Comment by bluepioupiou** [comment]
I don't really see the point of unit testing the component... what do you mean by that "unit testing" comparatively to "end2end testing". For me the important point is to see that the component still render correctly and respond to interractions, not to test that some method are sending the good output comparatively to inputs...

**Comment by soywod** [comment]
Indeed, there is not so much to unit test in this component. However, with this issue, I had in mind to refactor the core with `useReducer` and to separate the logic from the effects. This way it would be easy to unit test. Maybe I can first refactor, then you do the unit tests?

**Comment by bluepioupiou** [comment]
I was thinking the same thing : maybe we canevent separate between logic, effects and display and then we'll be able to set some unit tests on logic. But it can be better to create end2end test before so you'll see if you break something during refactor ?

**Comment by soywod** [comment]
Yes you right, so I'm doing them first and we see after for unit testing :)

**Comment by soywod** [comment]
I will continue the refactor (separate logic / effect), then you will be able to do the unit tests :)

**Comment by bluepioupiou** [comment]
great, looking for it

**Comment by soywod** [comment]
I finished the refactor: https://github.com/soywod/react-pin-field/compare/6c25d83b64fdc16687a3a9c3cf8ff162a16992c7...d824a46450b939bb23f2332fbd2eacd9f12fb125.
All the functions outside of the component can now be tested. I added a comment `//TODO: unit tests` at the top of them.

**Comment by soywod** [comment]
Unit tests with [Jest](https://jestjs.io/) and coverage with [Codecov](https://codecov.io/) set up in the last commit 87efd8fd02be2df908802663b3f5f926dd8d301f. Feel free to add some :)

**Comment by soywod** [comment]
Add component tests with [enzyme](https://airbnb.io/enzyme/) in 78055cfb12ff867c14fdae3d34beb62682c76c8a.
