### ISSUE TITLE
Error: Jest can't compile when react-pin-field is called in component

### ISSUE THREAD

**Issue by pedroSoaresll** [soywod/react-pin-field#20]
Hello @soywod 

I was using `react-pin-field` together @caiomdias but when we running Jest to test our components, we receive an error.

`jest error unexpected token import`

I did a fork of this repo and change the `module` inside `tsconfig.json` to `CommonJS`, so all working.
I think that other people could have this problem too, I don't know if have other solution for this but, if you want I can do a pull request with this change.

At this moment we are using another repository to solve `Pin Inputs`, but we really would like to use yours.

I tried the recommendations about this issue #18 but nothing worked.

PR: #21

**Comment by soywod** [comment]
You right, it should be definitely `CommonJS`, I will change it soon. Did you check [this issue](https://github.com/soywod/react-pin-field/issues/18)? It could fix meanwhile.

**Comment by pedroSoaresll** [comment]
@soywod thanks for your fast answer. And yes, I did the recommendations about issue #18 but nothing worked.

**Comment by pedroSoaresll** [comment]
> You right, it should definitely be `CommonJS`, I will change it soon. Did you check [this issue](https://github.com/soywod/react-pin-field/issues/18)? It could fix meanwhile.

I can open the PR and we can look at it together

**Comment by pedroSoaresll** [comment]
PR: #21

**Comment by pedroSoaresll** [comment]
Closing this issue. PR was merged. Thank you @soywod

**Comment by soywod** [comment]
Just released [v1.0.4](https://github.com/soywod/react-pin-field/releases/tag/v1.0.4), let me know if it fixes well your problem! Thank you for your feedback!

**Comment by pedroSoaresll** [comment]
> Just released [v1.0.4](https://github.com/soywod/react-pin-field/releases/tag/v1.0.4), let me know if it fixes well your problem! Thank you for your feedback!

Hey @soywod , all working fine! Thank you!
