### ISSUE TITLE
React 17 support?

### ISSUE THREAD

**Issue by devjoseluis** [soywod/react-pin-field#23]
When installing this package with the new version 17 of React it throws an error in the installation for the peer dependency of React version 16.

<img width="810" alt="Screen_Shot_2021-02-10" src="https://user-images.githubusercontent.com/8582458/107562362-554fc880-6ba5-11eb-941e-74c58d145b3c.png">

React 17 release: https://reactjs.org/blog/2020/10/20/react-v17.html

Thank you!

**Comment by soywod** [comment]
Fixed in `v1.0.6`. It took be a bit more time than expected because tests were failing. Feel free to reopen if sth does not work as expected. Thank you!
