### ISSUE TITLE
Feature request: Set initial value

### ISSUE THREAD

**Issue by Bloemendaal** [soywod/react-pin-field#25]
Hi! 

I was wondering if it is possible to set an initial value, e.g. when the code is already supplied in the query parameters.

Thanks :)

**Comment by soywod** [comment]
Theoretically you can do it thanks to the `ref`:

```typescript.tsx
const ref = useRef<HTMLInputElement[]>([]);

function setValue(pin: string) {
  if (ref.current) {
    ref.current.forEarch((input, idx) => {
      input.value = pin[idx];
    });
  }
}

return <PinField ref={ref} />;
```

Let me know if it helps you.

**Comment by Bloemendaal** [comment]
Cool! That works great! Thanks! 😁👏
