### ISSUE TITLE
build error on v2

### ISSUE THREAD

**Issue by mydearxym** [soywod/react-pin-field#31]
hi there ~

i try to use the latest version on npm, got

![image](https://user-images.githubusercontent.com/6184465/116172970-4f966780-a73e-11eb-8017-e714482d777c.png)

downgrade to 1.0.6 is fine ~

env: 

react-pin-field: v2.0.0-beta.0
@soywod/pin-field: 0.1.9

**Comment by soywod** [comment]
I will try to check this week and let you know. Thanks for the feedback!

**Comment by benjitastic** [comment]
same error for me unfortunately

**Comment by soywod** [comment]
It should work thanks to https://github.com/soywod/react-pin-field/pull/30, could you try again with the `v2.0.0-beta.1`?
