### ISSUE TITLE
I have problem "Uncaught TypeError: Cannot read property 'removeEventListener' of null" when unmount a component containing a react-pin-field

### ISSUE THREAD

**Issue by tiu93** [soywod/react-pin-field#38]
![image](https://user-images.githubusercontent.com/24446991/120308425-e7ffa900-c2f5-11eb-86f8-1fb7712008ab.png)

When I click on:
![image](https://user-images.githubusercontent.com/24446991/120308659-2ac18100-c2f6-11eb-8324-2366cbf16830.png)

I can see it:
![image](https://user-images.githubusercontent.com/24446991/120308604-19787480-c2f6-11eb-8175-a79e8f335442.png)

**Comment by soywod** [comment]
Thanks for your feedback, I will try to reproduce and let you know. I guess you are using the `v2.0.0-beta.X`?

**Comment by soywod** [comment]
Should be fixed by https://github.com/soywod/react-pin-field/pull/41

**Comment by soywod** [comment]
The 2.0.0-beta.2 should fix the issue, feel free to reopen if you still have this error!
