### ISSUE TITLE
Add a behaviour when key isn't allowed

### ISSUE THREAD

**Issue by bluepioupiou** [soywod/react-pin-field#4]
When we enter a key that is not allow, we don't really see that it's not a bug. Maybe display a red border hat shake a little before comming back to normal on the highlited input

**Comment by soywod** [comment]
The lib provides no style by default (and it's not the aim). What can be done is to add a new event when the user type a bad key. Or add a specific `className`. What do you think?

**Comment by bluepioupiou** [comment]
seems good enough for me !

**Comment by bluepioupiou** [comment]
I think the best will be to execute a method passed as props and let the responsible component decide what to do of that

**Comment by soywod** [comment]
Added both in d824a46450b939bb23f2332fbd2eacd9f12fb125:
- classes:
https://github.com/soywod/react-pin-field/blob/d824a46450b939bb23f2332fbd2eacd9f12fb125/src/pin-field.tsx#L173-L184
- callbacks:
https://github.com/soywod/react-pin-field/blob/d824a46450b939bb23f2332fbd2eacd9f12fb125/src/pin-field.types.ts#L8-L9
