### ISSUE TITLE
[bug] React state not synced on event callbacks

### ISSUE THREAD

**Issue by devjoseluis** [soywod/react-pin-field#45]
## Description
React local state values don't get updated on the `onChange` event callback prop of the `ReactPinField` component.

## Expected Behavior
The local state should be in sync when executing the `onChange` function.

## Actual Behavior
The local state value isn't in sync when executing the `onChange` function.

## Possible Fix
It is possible that mutating the original props object may cause this issue.
https://github.com/soywod/react-pin-field/blob/133b5a5ed4de523f9572117229e80989eed65aa4/src/index.ts#L30

## Steps to Reproduce
1. Add a local state to your app. (ex. `const [myState, setMyState] = useState("initialValue");`).
2. Define a function to handle the `ReactPinField` `onChange` event. (ex. `onChange={myHandlerFunction}`).
3. Add a local state usage in the handler function. (ex. `console.log(myState);`).
3. When the `onChange` event callback is triggered, the initial state value is logged in the console.
4. Update your local state value.
4. Trigger the `onChange` callback again; the console shows the initial state value instead of the updated value.

## Environment

* Version used: 2.0.0-beta.2
* Browser Name and version: Brave Browser V1.26.67 Chromium: 91.0.4472.114 (Official Build) (x86_64)
* Operating System and version: macOS Big Sur 11.4
* Link to demo: https://codesandbox.io/s/lucid-snyder-t3v2k

**Comment by soywod** [comment]
This may be linked to #44. The problem comes from the [web component](https://github.com/soywod/pin-field), React props are not __sync__ with it. I will investigate. Thanks!

**Comment by soywod** [comment]
The native web component was a big mistake, it led to so many issues… I ended up rolling back to `v1` state, without web component (pure React implementation). The issue should be fixed starting from the `v3.0.11`.
