### ISSUE TITLE
I can still type in some accent caracters ( ^ or ¨ )

### ISSUE THREAD

**Issue by bluepioupiou** [soywod/react-pin-field#5]
everything seems juste fin with other but a double tape on ^ or ¨ make them appears (and it doesn't pass to the next character)
![Capture d’écran de 2019-12-15 23-11-23](https://user-images.githubusercontent.com/3164314/70870174-4c0ea000-1f90-11ea-9fe6-3e4f1e1569cb.png)

**Comment by soywod** [comment]
I can't reproduce. On which OS and which browser did you try?

**Comment by bluepioupiou** [comment]
Ubuntu 18 and Chrome. It happens on regular input with preventDefault, out of React too

**Comment by soywod** [comment]
And which keyboard layout?

**Comment by bluepioupiou** [comment]
hmm, it's odd. I have french keyboard and layout, no particular configuration after Ubuntu installation. It happens when you type twice on the ^ or maj and ^ (which give you a ¨). No other key give me that

**Comment by soywod** [comment]
Could you give the output of `setxkbmap -query`? I bet it's because of a particular layout variant.

**Comment by bluepioupiou** [comment]
rules:      evdev
model:      pc105
layout:     fr,fr
variant:    azerty,oss

**Comment by soywod** [comment]
It bugs with both variant `azerty` and `oss`?

**Comment by bluepioupiou** [comment]
I don't know, I can't change variant... I only have this 
![Capture d’écran de 2019-12-16 14-41-27](https://user-images.githubusercontent.com/3164314/70911442-3641bf00-2012-11ea-8227-370c5fa3c339.png)

**Comment by bluepioupiou** [comment]
And when i'm using AltrGr + 9 (for another caret), indeed no car in the input. It's when i'm using the one near the 'p' letter

**Comment by soywod** [comment]
Still can't reproduce with the same configuration (I used the variant `azerty`).
If you tell me you have the same in a regular input with `preventDefault()`, I guess it comes from your installation (either OS or tools), not the lib. Did you try in an other browser?

**Comment by soywod** [comment]
Ah, reproduced with `fr` layout, `azerty` variant and Firefox `69.0.2 (64-bit)`. I will investigate.

**Comment by bluepioupiou** [comment]
Ok but I really installed "only" Ubuntu 18.04 and made no change about keyboard or anything else. It fails on Firefox too. What OS do you have ?

**Comment by bluepioupiou** [comment]
My chrome version is 78. And indeed I trie on window and on Mac and it's working fine ><

**Comment by soywod** [comment]
Arch Linux `5.3.1`, Chromium `77.0.3865.90`. Indeed, it's a dead key problem, but seems to be handled differently by the browsers :rofl:

**Comment by bluepioupiou** [comment]
it's working now, thanks for the modifications
