### ISSUE TITLE
 react-pin-field@2.0.0-beta.2" has incorrect peer dependency "@soywod/pin-field@^0.1.6"

### ISSUE THREAD

**Issue by luckyxhu** [soywod/react-pin-field#51]
when install react-pin-field, `yarn` give below warning:

```
 react-pin-field@2.0.0-beta.2" has incorrect peer dependency "@soywod/pin-field@^0.1.6"
```

**Comment by luckyxhu** [comment]
I have install `@soywod/pin-field` `0.2.1`

**Comment by soywod** [comment]
Yes, since the `v2` you need to install also `@soywod/pin-field`, see the installation guide.

**Comment by luckyxhu** [comment]
No, I mean i have already install `@soywod/pin-field` `0.2.1`, but still get the warning message. maybe is peer dependency version need upgrade to `^0.2`.

**Comment by luckyxhu** [comment]
Yes, the warning is gone, thank you.
