### ISSUE TITLE
debug prop should not be pass to input element

### ISSUE THREAD

**Issue by luckyxhu** [soywod/react-pin-field#57]
the prop `debug` is only for ReactPinField, pass to input element will cause warning:

```
Warning: Received `false` for a non-boolean attribute `debug`.

If you want to write it to the DOM, pass a string instead: debug="false" or debug={value.toString()}.

If you used to conditionally omit it with debug={condition && value}, pass debug={condition ? value : undefined} instead.
    at input
    at http://localhost:3333/static/js/bundle.js:182130:59
    at div
```  

currently we can pass `undefined` to debug to prevent this warning, but `debug={undefined}` look unlike what it should be.

**Comment by soywod** [comment]
Which version do you use?

**Comment by soywod** [comment]
The `debug` mode has been removed in the `v3.0.12`, the error should be fixed!
