### ISSUE TITLE
Should allow setting `type=number`

### ISSUE THREAD

**Issue by maged** [soywod/react-pin-field#90]
The `type` prop on the <input> fields should be able to be set from the PinField component.  This will allow using mobile browsers' numeric keyboards.

**Comment by soywod** [comment]
> The `type` prop on the <input> fields should be able to be set from
> the PinField component.

The component already forwards InputHTMLAttributes the inner inputs. So
type=number already works. You have an example at
<https://soywod.github.io/react-pin-field/> with type=password.

> This will allow using mobile browsers' numeric keyboards

You can also use inputMode. Try the demo from your mobile, you should
see appropriate keyboards showing up.

**Comment by maged** [comment]
You are right, that works -- thanks for the fast response! Closing the issue. I assumed it was hard coded based on this https://github.com/soywod/react-pin-field/blob/master/lib/src/pin-field/pin-field.tsx#L316 🤔

**Comment by soywod** [comment]
> I assumed it was hard coded

What you see is the default value, which can be overriden [just after](https://github.com/soywod/react-pin-field/blob/f3679d9b13237f51a6805fe226052f6d57f5674a/lib/src/pin-field/pin-field.tsx#L321).
